### ISSUE TITLE
javascript issues when using svg images in tab-list

### ISSUE THREAD

**Issue by hans2103** [2kool2/accessible-tabs#1]
thanks for the great work.

I've tried your solution but receive a javascript error on hover of tab-list-items when they are filled with svg images.
```
pen.js:100 Uncaught TypeError: Cannot read property 'classList' of undefined
    at HTMLAnchorElement._tabHovered (pen.js:100)
_tabHovered @ pen.js:100
```
See the forked codepen https://codepen.io/hans2103/pen/eEwzBz

Any suggestions how this can be fixed?

**Comment by 2kool2** [comment]
Hi Hans,
I don't know where that specific error comes from, I'll have a dig but the issue you describe is because you are clicking on the foreground SVG and not the background "button".
The solution is so simple you'll kick yourself.
Add to the CSS

    .a SVG {pointer-events: none;}

Does that help?

Mike

**Comment by hans2103** [comment]
@2kool2 that solved the trick.
I've added ```.tl_list svg {pointer-events: none;}``` to the created codepen and noticed that the issue is solved. 
thx

https://codepen.io/hans2103/pen/eEwzBz
